name: Publish PDFs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LATEX: /usr/bin/latexmk
      SOURCES: sources.txt
      OUTPUT_DIR: output

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Compile LaTeX documents
      run: |
        mkdir -p ${{ env.OUTPUT_DIR }}

        while IFS=' ' read -r source destination; do
          latexmk -pdf -interaction=nonstopmode -output-directory=${{ env.OUTPUT_DIR }} "$source"
          mv "${{ env.OUTPUT_DIR }}/${source%.tex}.pdf" "${{ env.OUTPUT_DIR }}/$destination"
        done < sources.txt
      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload PDFs to Release
      run: |
        for file in ${{ env.OUTPUT_DIR }}/*.pdf; do
          gh release upload ${{ steps.create_release.outputs.upload_url }} "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}