name: Publish PDFs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LATEX: /usr/bin/latexmk
      SOURCES: sources.txt

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Compile LaTeX documents
      run: |
        while IFS=' ' read -r source destination; do
          latexmk -pdf -interaction=nonstopmode -output-directory=output "$source"
          mv "output/${source%.tex}.pdf" "$destination"
        done < sources.txt

    - name: Install Ghostscript
      run: sudo apt-get install -y ghostscript
      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: combined.pdf
        asset_name: combined.pdf
        asset_content_type: application/pdf